### ISSUE TITLE
Update Installation Directory

### ISSUE THREAD

**Issue by adworjan** [ansible/metrics-utility#3]
For the installation in the README.md

For activate Controller's python virtual environment
The line: ". /var/lib/awx/venv/bin/activate" should be ". /var/lib/awx/venv/awx/bin/activate"

**Comment by slemrmartin** [comment]
https://github.com/ansible/metrics-utility/pull/4

**Comment by ffirg** [comment]
@slemrmartin can we get this PR from Alex merged? I've just encountered the same issue (Rich asked me to test and validate). Thanks.

**Comment by slemrmartin** [comment]
@ffirg merged

**Comment by ffirg** [comment]
thanks Martin!
